
package views;

import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.bean.Pessoa;
import model.bean.PessoaFisica;
import util.Util;

/**
 * @author enaldo.souza
 */
public class JFCadastroPessoa extends javax.swing.JFrame {

    Util formData  = new Util();
    Util formEmail = new Util();
    Util formCpf   = new Util();
    Util formCnpj  = new Util();
    
    public JFCadastroPessoa() {
        initComponents();
        
        //estados
        jCBestadoIden.addItem("ESCOLHA");
        jCBestadoIden.addItem("ACRE (RIO BRANCO)");
        jCBestadoIden.addItem("ALAGOAS (MACEIÓ)");
        jCBestadoIden.addItem("AMAPÁ (MACAPÁ)");
        jCBestadoIden.addItem("AMAZONAS (MANAUS)");
        jCBestadoIden.addItem("BAHIA (SALVADOR)");
        jCBestadoIden.addItem("CEARÁ (FORTALEZA)");
        jCBestadoIden.addItem("DISTRITO FEDERAL (BRASÍLIA)");
        jCBestadoIden.addItem("ESPÍRITO SANTO (VITÓRIA)");
        jCBestadoIden.addItem("GOIÁS (GOIÂNIA)");
        jCBestadoIden.addItem("MARANHÃO (SÃO LUÍS)");
        jCBestadoIden.addItem("MATO GROSSO (CUIABÁ)");
        jCBestadoIden.addItem("MATO GROSSO DO SUL (CAMPO GRANDE)");
        jCBestadoIden.addItem("MINAS GERAIS (BELO HORIZONTE)");
        jCBestadoIden.addItem("PARÁ (BELÉM)");
        jCBestadoIden.addItem("PARAÍBA (JOÃO PESSOA)");
        jCBestadoIden.addItem("PARANÁ (CURITIBA)");
        jCBestadoIden.addItem("PERNAMBUCO (RECIFE)");
        jCBestadoIden.addItem("PIAUÍ (TERESINA)");
        jCBestadoIden.addItem("RIO DE JANEIRO (RIO DE JANEIRO)");
        jCBestadoIden.addItem("RIO GRANDE DO NORTE (NATAL)");
        jCBestadoIden.addItem("RIO GRANDE DO SUL (PORTO ALEGRE)");
        jCBestadoIden.addItem("RONDÔNIA (PORTO VELHO)");
        jCBestadoIden.addItem("RORAIMA (BOA VISTA)");
        jCBestadoIden.addItem("SANTA CATARINA (FLORIANÓPOLIS)");
        jCBestadoIden.addItem("SÃO PAULO (SÃO PAULO)");
        jCBestadoIden.addItem("SERGIPE (ARACAJU)");
        jCBestadoIden.addItem("TOCANTIS (PALMAS)");
        
        //orgãos expeditores
        jComboBoxOrgExpeditor.addItem("ESCOLHA");
        jComboBoxOrgExpeditor.addItem("SSP - Secretaria de Segurança Pública");
        jComboBoxOrgExpeditor.addItem("PM - Polícia Militar");
        jComboBoxOrgExpeditor.addItem("PC - Policia Civil");
        jComboBoxOrgExpeditor.addItem("CNT - Carteira Nacional de Habilitação");
        jComboBoxOrgExpeditor.addItem("IC - Diretoria de Identificação Civil");
        jComboBoxOrgExpeditor.addItem("CTPS - Carteira de Trabaho e Previdência Social");
        jComboBoxOrgExpeditor.addItem("FGTS - Fundo de Garantia do Tempo de Serviço");
        jComboBoxOrgExpeditor.addItem("IFP - Instituto Félix Pacheco");
        jComboBoxOrgExpeditor.addItem("IPF - Instituto Pereira Faustino");
        jComboBoxOrgExpeditor.addItem("IML - Instituto Médico-Legal");
        jComboBoxOrgExpeditor.addItem("MTE - Ministério do Trabalho e Emprego");
        jComboBoxOrgExpeditor.addItem("MMA - Ministério da Marinha");
        jComboBoxOrgExpeditor.addItem("MAE - Ministério da Aeronáutica");
        jComboBoxOrgExpeditor.addItem("MEX - Ministério do Exército");
        jComboBoxOrgExpeditor.addItem("POF - Polícia Federal");
        jComboBoxOrgExpeditor.addItem("POM - Polícia Militar");
        jComboBoxOrgExpeditor.addItem("SES - Carteira de Estrangeiro");
        jComboBoxOrgExpeditor.addItem("SJS - Secretaria da Justiça e Segurança");
        jComboBoxOrgExpeditor.addItem("SJTS - Secretaria da Justiça do Trabalho e Segurança");
        jComboBoxOrgExpeditor.addItem("ZZZ - Outros (inclusive exterior) ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPCadastroPessoa = new javax.swing.JPanel();
        jBinserirPessoa = new javax.swing.JButton();
        jBalterarPessoa = new javax.swing.JButton();
        jBremoverPessoa = new javax.swing.JButton();
        jBlimparPessoa = new javax.swing.JButton();
        jBcancelarPessoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTcadastroPessoa = new javax.swing.JTable();
        jTabbedPaneCadastroDadosPessoais = new javax.swing.JTabbedPane();
        jPanelDadosPessoais = new javax.swing.JPanel();
        jLabelNomePessoa = new javax.swing.JLabel();
        jTFnomePessoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFcnpj = new javax.swing.JFormattedTextField();
        jLBemailPessoa = new javax.swing.JLabel();
        jTextfEmailPessoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFdataNascPessoa = new javax.swing.JFormattedTextField();
        jLidentidade = new javax.swing.JLabel();
        jTFidentidade = new javax.swing.JTextField();
        jLorgaoExpeditor = new javax.swing.JLabel();
        jLestadoIdentidade = new javax.swing.JLabel();
        jCBestadoIden = new javax.swing.JComboBox<>();
        jComboBoxOrgExpeditor = new javax.swing.JComboBox<>();
        jLabelSexo = new javax.swing.JLabel();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jLabelNomeMae = new javax.swing.JLabel();
        jTextFieldNomeMae = new javax.swing.JTextField();
        jLabelNomePai = new javax.swing.JLabel();
        jTextFieldNomePai = new javax.swing.JTextField();
        jPanelDadosComplementares = new javax.swing.JPanel();
        jLabelEnderecoPessoa = new javax.swing.JLabel();
        jTextFieldEnderecoPessoa = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidadeEndereco = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldTelefonePessoa = new javax.swing.JFormattedTextField();
        jLabelCelularPessoa = new javax.swing.JLabel();
        jFormattedTextFieldCelularPessoa = new javax.swing.JFormattedTextField();
        jComboBoxEstadoEnd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPCadastroPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBinserirPessoa.setText("Inserir");
        jBinserirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirPessoaActionPerformed(evt);
            }
        });

        jBalterarPessoa.setText("Alterar");

        jBremoverPessoa.setText("Remover");

        jBlimparPessoa.setText("Limpar");
        jBlimparPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparPessoaActionPerformed(evt);
            }
        });

        jBcancelarPessoa.setText("Cancelar");
        jBcancelarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroPessoaLayout = new javax.swing.GroupLayout(jPCadastroPessoa);
        jPCadastroPessoa.setLayout(jPCadastroPessoaLayout);
        jPCadastroPessoaLayout.setHorizontalGroup(
            jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBinserirPessoa)
                .addGap(17, 17, 17)
                .addComponent(jBalterarPessoa)
                .addGap(18, 18, 18)
                .addComponent(jBremoverPessoa)
                .addGap(18, 18, 18)
                .addComponent(jBlimparPessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancelarPessoa)
                .addContainerGap())
        );
        jPCadastroPessoaLayout.setVerticalGroup(
            jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPessoaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinserirPessoa)
                    .addComponent(jBalterarPessoa)
                    .addComponent(jBremoverPessoa)
                    .addComponent(jBlimparPessoa)
                    .addComponent(jBcancelarPessoa))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro de Pessoa");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTcadastroPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD_PESSOA", "NOME PESSOA", "TIPO_PESSOA", "CPF", "RG", "DATA_NASC", "TELEFONE_RESIDENCIAL", "TELEFONE_COMERCIAL", "TELEFONE_CELULAR", "CNPJ", "IE", "IM", "NOME_FANTASIA", "COD_CIDADE", "NOME_CIDADE", "LOGRADOURO", "TIPO", "NÚMERO", "BAIRRO", "CEP", "ESTADO", "DATA_CADASTRO", "DATA_DESATIVACAO"
            }
        ));
        jScrollPane1.setViewportView(jTcadastroPessoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabelNomePessoa.setText("Nome: *");

        jTFnomePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnomePessoaKeyTyped(evt);
            }
        });

        jLabel2.setText("Cpf: *");

        try {
            jFormattedTextCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextCpfKeyTyped(evt);
            }
        });

        jLabel3.setText("Cnpj: *");

        try {
            jFormattedTextFcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFcnpjActionPerformed(evt);
            }
        });
        jFormattedTextFcnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFcnpjKeyTyped(evt);
            }
        });

        jLBemailPessoa.setText("E-mail: *  (exemplo: email@teste.com.br)");

        jTextfEmailPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfEmailPessoaActionPerformed(evt);
            }
        });
        jTextfEmailPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextfEmailPessoaKeyTyped(evt);
            }
        });

        jLabel4.setText("Data Nascimento: *");

        try {
            jFormattedTextFdataNascPessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFdataNascPessoa.setToolTipText("");
        jFormattedTextFdataNascPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFdataNascPessoaKeyTyped(evt);
            }
        });

        jLidentidade.setText("Identidae: *");

        jTFidentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidentidadeActionPerformed(evt);
            }
        });
        jTFidentidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFidentidadeKeyTyped(evt);
            }
        });

        jLorgaoExpeditor.setText("Orgão Expeditor: *");

        jLestadoIdentidade.setText("Estado: *");

        jCBestadoIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA", "ACRE (RIO BRANCO)", "ALAGOAS (MACEIÓ)", "AMAPÁ (MACAPÁ)", "AMAZONAS (MANAUS)", "BAHIA (SALVADOR)", "CEARÁ (FORTALEZA)", "DISTRITO FEDERAL (BRASÍLIA)", "ESPÍRITO SANTO (VITÓRIA)", "GOIÁS (GOIÂNIA)", "MARANHÃO (SÃO LUÍS)", "MATO GROSSO (CUIABÁ)", "MATO GROSSO DO SUL (CAMPO GRANDE)", "MINAS GERAIS (BELO HORIZONTE)", "PARÁ (BELÉM)", "PARAÍBA (JOÃO PESSOA)", "PARANÁ (CURITIBA)", "PERNAMBUCO (RECIFE)", "PIAUÍ (TERESINA)", "RIO DE JANEIRO (RIO DE JANEIRO)", "RIO GRANDE DO NORTE (NATAL)", "RIO GRANDE DO SUL (PORTO ALEGRE)", "RONDÔNIA (PORTO VELHO)", "RORAIMA (BOA VISTA)", "SANTA CATARINA (FLORIANÓPOLIS)", "SÃO PAULO (SÃO PAULO)", "SERGIPE (ARACAJU)", "TOCANTIS (PALMAS)" }));

        jComboBoxOrgExpeditor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA", "SSP - Secretaria de Segurança Pública", "PM - Polícia Militar", "PC - Policia Civil", "CNT - Carteira Nacional de Habilitação", "IC - Diretoria de Identificação Civil", "CTPS - Carteira de Trabaho e Previdência Social", "FGTS - Fundo de Garantia do Tempo de Serviço", "IFP - Instituto Félix Pacheco", "IPF - Instituto Pereira Faustino", "IML - Instituto Médico-Legal", "MTE - Ministério do Trabalho e Emprego", "MMA - Ministério da Marinha", "MAE - Ministério da Aeronáutica", "MEX - Ministério do Exército", "POF - Polícia Federal", "POM - Polícia Militar", "SES - Carteira de Estrangeiro", "SJS - Secretaria da Justiça e Segurança", "SJTS - Secretaria da Justiça do Trabalho e Segurança", "ZZZ - Outros (inclusive exterior)" }));

        jLabelSexo.setText("Sexo: *");

        buttonGroupSexo.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("FEMININO");
        jRadioButtonFeminino.setActionCommand("feminino");

        buttonGroupSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setSelected(true);
        jRadioButtonMasculino.setText("MASCULINO");
        jRadioButtonMasculino.setActionCommand("masculino");

        jLabelNomeMae.setText("Nome da Mãe: *");

        jTextFieldNomeMae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeMaeKeyTyped(evt);
            }
        });

        jLabelNomePai.setText("Nome do Pai: *");

        jTextFieldNomePai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomePaiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosPessoaisLayout = new javax.swing.GroupLayout(jPanelDadosPessoais);
        jPanelDadosPessoais.setLayout(jPanelDadosPessoaisLayout);
        jPanelDadosPessoaisLayout.setHorizontalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomePessoa)
                            .addComponent(jTFnomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jFormattedTextFdataNascPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSexo)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jRadioButtonFeminino)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMasculino)))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLidentidade)
                                    .addComponent(jTFidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLestadoIdentidade)
                                    .addComponent(jCBestadoIden, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFormattedTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelNomeMae)
                            .addComponent(jTextFieldNomeMae))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabelNomePai)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLorgaoExpeditor))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextfEmailPessoa)
                                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLBemailPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jTextFieldNomePai))))
                .addContainerGap())
        );
        jPanelDadosPessoaisLayout.setVerticalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelNomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFdataNascPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFeminino)
                            .addComponent(jRadioButtonMasculino))))
                .addGap(16, 16, 16)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLidentidade)
                            .addComponent(jLestadoIdentidade)
                            .addComponent(jLorgaoExpeditor)
                            .addComponent(jLBemailPessoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBestadoIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextfEmailPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeMae)
                    .addComponent(jLabelNomePai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneCadastroDadosPessoais.addTab("Dados Pessoais", jPanelDadosPessoais);

        jLabelEnderecoPessoa.setText("Endereço: *");

        jTextFieldEnderecoPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEnderecoPessoaKeyTyped(evt);
            }
        });

        jLabelNumero.setText("Número: *");

        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jLabelComplemento.setText("Complemento: *");

        jTextFieldComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyTyped(evt);
            }
        });

        jLabelBairro.setText("Bairro: *");

        jTextFieldBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyTyped(evt);
            }
        });

        jLabel5.setText("Estado: *");

        jLabelCidade.setText("Cidade: *");

        jTextFieldCidadeEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCidadeEnderecoKeyTyped(evt);
            }
        });

        jLabelCep.setText("Cep: *");

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCepKeyTyped(evt);
            }
        });

        jLabelTelefone.setText("Telefone: *");

        try {
            jFormattedTextFieldTelefonePessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefonePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldTelefonePessoaKeyTyped(evt);
            }
        });

        jLabelCelularPessoa.setText("Celular: *");

        try {
            jFormattedTextFieldCelularPessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCelularPessoaKeyTyped(evt);
            }
        });

        jComboBoxEstadoEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA", "ACRE (RIO BRANCO)", "ALAGOAS (MACEIÓ)", "AMAPÁ (MACAPÁ)", "AMAZONAS (MANAUS)", "BAHIA (SALVADOR)", "CEARÁ (FORTALEZA)", "DISTRITO FEDERAL (BRASÍLIA)", "ESPÍRITO SANTO (VITÓRIA)", "GOIÁS (GOIÂNIA)", "MARANHÃO (SÃO LUÍS)", "MATO GROSSO (CUIABÁ)", "MATO GROSSO DO SUL (CAMPO GRANDE)", "MINAS GERAIS (BELO HORIZONTE)", "PARÁ (BELÉM)", "PARAÍBA (JOÃO PESSOA)", "PARANÁ (CURITIBA)", "PERNAMBUCO (RECIFE)", "PIAUÍ (TERESINA)", "RIO DE JANEIRO (RIO DE JANEIRO)", "RIO GRANDE DO NORTE (NATAL)", "RIO GRANDE DO SUL (PORTO ALEGRE)", "RONDÔNIA (PORTO VELHO)", "RORAIMA (BOA VISTA)", "SANTA CATARINA (FLORIANÓPOLIS)", "SÃO PAULO (SÃO PAULO)", "SERGIPE (ARACAJU)", "TOCANTIS (PALMAS)" }));

        javax.swing.GroupLayout jPanelDadosComplementaresLayout = new javax.swing.GroupLayout(jPanelDadosComplementares);
        jPanelDadosComplementares.setLayout(jPanelDadosComplementaresLayout);
        jPanelDadosComplementaresLayout.setHorizontalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabelBairro)
                                .addGap(231, 231, 231))
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxEstadoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabelEnderecoPessoa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEnderecoPessoa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumero)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelComplemento)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCep))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone)
                            .addComponent(jFormattedTextFieldTelefonePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCelularPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelularPessoa))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosComplementaresLayout.setVerticalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoPessoa)
                    .addComponent(jLabelNumero)
                    .addComponent(jLabelComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnderecoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabel5)
                    .addComponent(jLabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstadoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelCep)
                    .addComponent(jLabelCelularPessoa))
                .addGap(6, 6, 6)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefonePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelularPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPaneCadastroDadosPessoais.addTab("Dados Complementares", jPanelDadosComplementares);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCadastroPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneCadastroDadosPessoais))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneCadastroDadosPessoais)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(907, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFcnpjActionPerformed

    private void jTextfEmailPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfEmailPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfEmailPessoaActionPerformed

    private void jTFidentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidentidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidentidadeActionPerformed

    private void jTFnomePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnomePessoaKeyTyped

        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        
        if((Character.isDigit(c))    || c==KeyEvent.VK_BACK_SPACE    || c==KeyEvent.VK_DELETE           || c==KeyEvent.VK_COMMA 
            || c==KeyEvent.VK_AT     || c==KeyEvent.VK_CIRCUMFLEX    || c==KeyEvent.VK_BACK_SLASH       || c==KeyEvent.VK_UNDERSCORE 
            || c==KeyEvent.VK_AT     || c==KeyEvent.VK_CLOSE_BRACKET || c==KeyEvent.VK_COLON            || c==KeyEvent.VK_SLASH 
            || c==KeyEvent.VK_DOLLAR || c==KeyEvent.VK_EQUALS        || c==KeyEvent.VK_EXCLAMATION_MARK || c==KeyEvent.VK_LEFT_PARENTHESIS
            || c==KeyEvent.VK_MINUS  || c==KeyEvent.VK_NUMBER_SIGN   || c==KeyEvent.VK_OPEN_BRACKET     || c==KeyEvent.VK_RIGHT_PARENTHESIS
            || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_PLUS          || c==KeyEvent.VK_SEMICOLON){
            
                evt.consume();
        }        
    }//GEN-LAST:event_jTFnomePessoaKeyTyped

 
    private void jBinserirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirPessoaActionPerformed
        
        String nomePessoa = jTFnomePessoa.getText().toLowerCase();
        
        //formata data
        String dataFormatada = "";
        String dtNasc        = jFormattedTextFdataNascPessoa.getText();
        dtNasc = dtNasc.trim();
        
        //captura botão
        String sexo = buttonGroupSexo.getSelection().getActionCommand();
        sexo = sexo.equals("feminino") ? "FEMININO" : "MASCULINO";
        
        String identidade = jTFidentidade.getText();
        String estadoId   = jCBestadoIden.getSelectedItem().toString();
        String orgExped   = jCBestadoIden.getSelectedItem().toString();
        String email      = jTextfEmailPessoa.getText();

        //prepara cpf
        String cpf = jFormattedTextCpf.getText();
        cpf = cpf.trim();

        //prepara cnpj
        String cnpj = jFormattedTextFcnpj.getText();
        cnpj = cnpj.trim();
        
        String nomeMae   = jTextFieldNomeMae.getText().toUpperCase();
        String nomePai   = jTextFieldNomePai.getText().toUpperCase();
        String endereco  = jTextFieldEnderecoPessoa.getText().toLowerCase();
        String numero    = jTextFieldNumero.getText();
        String complemen = jTextFieldComplemento.getText().toLowerCase();
        String bairro    = jTextFieldBairro.getText().toLowerCase();
        String estadoEnd = jComboBoxEstadoEnd.getSelectedItem().toString();
        String cidade    = jTextFieldCidadeEndereco.getText().toLowerCase();
        String cep       = jFormattedTextFieldCep.getText();
        String foneFixo  = jFormattedTextFieldTelefonePessoa.getText();
        String celular   = jFormattedTextFieldCelularPessoa.getText();
        
        boolean retornoEmail = false;

        if( nomePessoa.isEmpty()           || sexo.isEmpty()             || identidade.isEmpty()
            || estadoId.equals("ESCOLHA")  || orgExped.equals("ESCOLHA") || email.isEmpty()
            || cpf.length()< 11            || cnpj.length()< 18          || dtNasc.length()< 10
            || nomeMae.isEmpty()           || nomePai.isEmpty()          || endereco.isEmpty()
            || numero.isEmpty()            || complemen.isEmpty()        || bairro.isEmpty()
            || estadoEnd.equals("ESCOLHA") || cidade.isEmpty()           || cep.isEmpty()
            || foneFixo.isEmpty()          || celular.isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!",
            "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(!retornoEmail){

            dataFormatada = formData.transformaData(dtNasc);
            retornoEmail  = formEmail.validaEmail(email);

            if(retornoEmail){
                
                Pessoa pessoa = new Pessoa();
                PessoaFisica pFisica = new PessoaFisica();
                
                
                pessoa.setUf(estadoId);
                pessoa.setNome(nomePessoa);
                
                pFisica.setSexo(sexo);
                pFisica.setRg(identidade);
                pessoa.
                
                
                
                
                System.out.println("Email: " + email);  
                //chama dao para e grava dtNasc no banco
                System.out.println("Data Nasc.: " + dataFormatada);
                
                //verifica Cnpj
                boolean ehCnpj = formCnpj.isCNPJ(cnpj);
                if(ehCnpj){
                    
                    //retira ponto(.) , traço(-) e barra(/) da string cnpj
                    cnpj = Pattern.compile("\\.+").matcher(cnpj).replaceAll("");
                    cnpj = Pattern.compile("\\-+").matcher(cnpj).replaceAll("");        
                    cnpj = Pattern.compile("\\/+").matcher(cnpj).replaceAll("");
        
                    //envia cnpj para o banco via dao
                    System.out.println("Cnpj: " + cnpj);
        
                }else{
                    JOptionPane.showMessageDialog(this, "Cnpj inválido. Redigite!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);        
                }
        
              //verifica cpf
                boolean ehCpf = formCpf.isCPF(cpf);
                if(ehCpf){

                    //retira . e - da string cpf
                    cpf = Pattern.compile("\\.+").matcher(cpf).replaceAll("");
                    cpf = Pattern.compile("\\-+").matcher(cpf).replaceAll("");
                    //envia cpf para o banco via Dao
                    System.out.println("Cpf: " + cpf);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Cpf inválido. Redigite!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);                    
                }
//                System.out.println( ehCpf ? "Válido: " + cpf  : "Inválido: " + cpf);
                
            }else{  
                JOptionPane.showMessageDialog(this, "Email inválido, redigite!",
                "Aviso", JOptionPane.WARNING_MESSAGE);                
            }
        }
    }//GEN-LAST:event_jBinserirPessoaActionPerformed

    private void jTextfEmailPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextfEmailPessoaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextfEmailPessoaKeyTyped

    private void jBlimparPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimparPessoaActionPerformed

        jTFnomePessoa.setText("");
        jFormattedTextFdataNascPessoa.setText("");
        jTFidentidade.setText("");  
        jCBestadoIden.setSelectedItem("ESCOLHA");
        jComboBoxOrgExpeditor.setSelectedItem("ESCOLHA");
        jTextfEmailPessoa.setText("");
        jFormattedTextCpf.setText("");
        jFormattedTextFcnpj.setText("");
        jTextFieldNomeMae.setText("");
        jTextFieldNomePai.setText("");  
        jTextFieldEnderecoPessoa.setText("");
        jTextFieldNumero.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidadeEndereco.setText("");
        jComboBoxEstadoEnd.setSelectedItem("ESCOLHA");
        jFormattedTextFieldCep.setText("");        
        jFormattedTextFieldTelefonePessoa.setText("");
        jFormattedTextFieldCelularPessoa.setText("");
    }//GEN-LAST:event_jBlimparPessoaActionPerformed

    private void jBcancelarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarPessoaActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarPessoaActionPerformed

    private void jTFidentidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFidentidadeKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTFidentidadeKeyTyped

    private void jTextFieldNomeMaeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeMaeKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextFieldNomeMaeKeyTyped

    private void jTextFieldNomePaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomePaiKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextFieldNomePaiKeyTyped

    private void jTextFieldEnderecoPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoPessoaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextFieldEnderecoPessoaKeyTyped

    private void jTextFieldBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextFieldBairroKeyTyped

    private void jTextFieldComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTextFieldComplementoKeyTyped

    private void jTextFieldCidadeEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeEnderecoKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        
        if((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCidadeEnderecoKeyTyped

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped

        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume(); 
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jFormattedTextFieldTelefonePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefonePessoaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume();         
    }//GEN-LAST:event_jFormattedTextFieldTelefonePessoaKeyTyped

    private void jFormattedTextFieldCelularPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularPessoaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume(); 
    }//GEN-LAST:event_jFormattedTextFieldCelularPessoaKeyTyped

    private void jFormattedTextFieldCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepKeyTyped

        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume();         
    }//GEN-LAST:event_jFormattedTextFieldCepKeyTyped

    private void jFormattedTextFdataNascPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFdataNascPessoaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume(); 
    }//GEN-LAST:event_jFormattedTextFdataNascPessoaKeyTyped

    private void jFormattedTextFcnpjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFcnpjKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume(); 
    }//GEN-LAST:event_jFormattedTextFcnpjKeyTyped

    private void jFormattedTextCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextCpfKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
          evt.setKeyChar(Character.toUpperCase(c));
        }
        if(!Character.isDigit(c)) evt.consume(); 
    }//GEN-LAST:event_jFormattedTextCpfKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jBalterarPessoa;
    private javax.swing.JButton jBcancelarPessoa;
    private javax.swing.JButton jBinserirPessoa;
    private javax.swing.JButton jBlimparPessoa;
    private javax.swing.JButton jBremoverPessoa;
    private javax.swing.JComboBox<String> jCBestadoIden;
    private javax.swing.JComboBox<String> jComboBoxEstadoEnd;
    private javax.swing.JComboBox<String> jComboBoxOrgExpeditor;
    private javax.swing.JFormattedTextField jFormattedTextCpf;
    private javax.swing.JFormattedTextField jFormattedTextFcnpj;
    private javax.swing.JFormattedTextField jFormattedTextFdataNascPessoa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularPessoa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePessoa;
    private javax.swing.JLabel jLBemailPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelularPessoa;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEnderecoPessoa;
    private javax.swing.JLabel jLabelNomeMae;
    private javax.swing.JLabel jLabelNomePai;
    private javax.swing.JLabel jLabelNomePessoa;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLestadoIdentidade;
    private javax.swing.JLabel jLidentidade;
    private javax.swing.JLabel jLorgaoExpeditor;
    private javax.swing.JPanel jPCadastroPessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDadosComplementares;
    private javax.swing.JPanel jPanelDadosPessoais;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFidentidade;
    private javax.swing.JTextField jTFnomePessoa;
    private javax.swing.JTabbedPane jTabbedPaneCadastroDadosPessoais;
    private javax.swing.JTable jTcadastroPessoa;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidadeEndereco;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEnderecoPessoa;
    private javax.swing.JTextField jTextFieldNomeMae;
    private javax.swing.JTextField jTextFieldNomePai;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextfEmailPessoa;
    // End of variables declaration//GEN-END:variables
}
