
package views;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 * @author enaldo.souza
 */
public class JFCadastroPessoa extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastroPessoa
     */
    public JFCadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPCadastroPessoa = new javax.swing.JPanel();
        jBinserirPessoa = new javax.swing.JButton();
        jBalterarPessoa = new javax.swing.JButton();
        jBremoverPessoa = new javax.swing.JButton();
        jBlimparPessoa = new javax.swing.JButton();
        jBcancelarPessoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTcadastroPessoa = new javax.swing.JTable();
        jTabbedPaneCadastroDadosPessoais = new javax.swing.JTabbedPane();
        jPanelDadosPessoais = new javax.swing.JPanel();
        jLabelNomePessoa = new javax.swing.JLabel();
        jTFnomePessoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFcnpj = new javax.swing.JFormattedTextField();
        jLBemailPessoa = new javax.swing.JLabel();
        jTextFemailPessoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFdataNascPessoa = new javax.swing.JFormattedTextField();
        jLidentidade = new javax.swing.JLabel();
        jTFidentidade = new javax.swing.JTextField();
        jLorgaoExpeditor = new javax.swing.JLabel();
        jLestadoIdentidade = new javax.swing.JLabel();
        jComboBoxEstadoIdentidade = new javax.swing.JComboBox<>();
        jComboBoxOrgExpeditor = new javax.swing.JComboBox<>();
        jLabelSexo = new javax.swing.JLabel();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jLabelNomeMae = new javax.swing.JLabel();
        jTextFieldNomeMae = new javax.swing.JTextField();
        jLabelNomePai = new javax.swing.JLabel();
        jTextFieldNomePai = new javax.swing.JTextField();
        jPanelDadosComplementares = new javax.swing.JPanel();
        jLabelEnderecoPessoa = new javax.swing.JLabel();
        jTextFieldEnderecoPessoa = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstadoEndereco = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidadeEndereco = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldTelefonePessoa = new javax.swing.JFormattedTextField();
        jLabelCelularPessoa = new javax.swing.JLabel();
        jFormattedTextFieldCelularPessoa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPCadastroPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBinserirPessoa.setText("Inserir");
        jBinserirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirPessoaActionPerformed(evt);
            }
        });

        jBalterarPessoa.setText("Alterar");

        jBremoverPessoa.setText("Remover");

        jBlimparPessoa.setText("Limpar");

        jBcancelarPessoa.setText("Cancelar");

        javax.swing.GroupLayout jPCadastroPessoaLayout = new javax.swing.GroupLayout(jPCadastroPessoa);
        jPCadastroPessoa.setLayout(jPCadastroPessoaLayout);
        jPCadastroPessoaLayout.setHorizontalGroup(
            jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBinserirPessoa)
                .addGap(17, 17, 17)
                .addComponent(jBalterarPessoa)
                .addGap(18, 18, 18)
                .addComponent(jBremoverPessoa)
                .addGap(18, 18, 18)
                .addComponent(jBlimparPessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancelarPessoa)
                .addContainerGap())
        );
        jPCadastroPessoaLayout.setVerticalGroup(
            jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPessoaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCadastroPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinserirPessoa)
                    .addComponent(jBalterarPessoa)
                    .addComponent(jBremoverPessoa)
                    .addComponent(jBlimparPessoa)
                    .addComponent(jBcancelarPessoa))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro de Pessoa");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTcadastroPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD_PESSOA", "NOME PESSOA", "TIPO_PESSOA", "CPF", "RG", "DATA_NASC", "TELEFONE_RESIDENCIAL", "TELEFONE_COMERCIAL", "TELEFONE_CELULAR", "CNPJ", "IE", "IM", "NOME_FANTASIA", "COD_CIDADE", "NOME_CIDADE", "LOGRADOURO", "TIPO", "NÚMERO", "BAIRRO", "CEP", "ESTADO", "DATA_CADASTRO", "DATA_DESATIVACAO"
            }
        ));
        jScrollPane1.setViewportView(jTcadastroPessoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabelNomePessoa.setText("Nome: *");

        jTFnomePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnomePessoaKeyTyped(evt);
            }
        });

        jLabel2.setText("Cpf: *");

        try {
            jFormattedTextCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Cnpj: *");

        try {
            jFormattedTextFcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFcnpjActionPerformed(evt);
            }
        });

        jLBemailPessoa.setText("E-mail: *");

        jTextFemailPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFemailPessoaActionPerformed(evt);
            }
        });
        jTextFemailPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFemailPessoaKeyTyped(evt);
            }
        });

        jLabel4.setText("Data Nascimento: *");

        try {
            jFormattedTextFdataNascPessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFdataNascPessoa.setToolTipText("");

        jLidentidade.setText("Identidae: *");

        jTFidentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidentidadeActionPerformed(evt);
            }
        });

        jLorgaoExpeditor.setText("Orgão Expeditor: *");

        jLestadoIdentidade.setText("Estado: *");

        jComboBoxEstadoIdentidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxOrgExpeditor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSexo.setText("Sexo: *");

        buttonGroupSexo.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("FEMININO");
        jRadioButtonFeminino.setActionCommand("feminino");

        buttonGroupSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setSelected(true);
        jRadioButtonMasculino.setText("MASCULINO");
        jRadioButtonMasculino.setActionCommand("masculino");

        jLabelNomeMae.setText("Nome da Mãe: *");

        jLabelNomePai.setText("Nome do Pai: *");

        javax.swing.GroupLayout jPanelDadosPessoaisLayout = new javax.swing.GroupLayout(jPanelDadosPessoais);
        jPanelDadosPessoais.setLayout(jPanelDadosPessoaisLayout);
        jPanelDadosPessoaisLayout.setHorizontalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomePessoa)
                            .addComponent(jTFnomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jFormattedTextFdataNascPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSexo)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jRadioButtonFeminino)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMasculino)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLidentidade)
                                    .addComponent(jTFidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLestadoIdentidade)
                                    .addComponent(jComboBoxEstadoIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFormattedTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelNomeMae)
                            .addComponent(jTextFieldNomeMae))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabelNomePai)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLorgaoExpeditor))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLBemailPessoa)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFemailPessoa)))
                            .addComponent(jTextFieldNomePai))))
                .addContainerGap())
        );
        jPanelDadosPessoaisLayout.setVerticalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelNomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFdataNascPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFeminino)
                            .addComponent(jRadioButtonMasculino))))
                .addGap(16, 16, 16)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLidentidade)
                            .addComponent(jLestadoIdentidade)
                            .addComponent(jLorgaoExpeditor)
                            .addComponent(jLBemailPessoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFidentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxEstadoIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFemailPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeMae)
                    .addComponent(jLabelNomePai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPaneCadastroDadosPessoais.addTab("Dados Pessoais", jPanelDadosPessoais);

        jLabelEnderecoPessoa.setText("Endereço: *");

        jLabelNumero.setText("Número: *");

        jLabelComplemento.setText("Complemento: *");

        jLabelBairro.setText("Bairro: *");

        jLabel5.setText("Estado: *");

        jLabelCidade.setText("Cidade: *");

        jLabelCep.setText("Cep: *");

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelTelefone.setText("Telefone: *");

        try {
            jFormattedTextFieldTelefonePessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCelularPessoa.setText("Celular: *");

        try {
            jFormattedTextFieldCelularPessoa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelDadosComplementaresLayout = new javax.swing.GroupLayout(jPanelDadosComplementares);
        jPanelDadosComplementares.setLayout(jPanelDadosComplementaresLayout);
        jPanelDadosComplementaresLayout.setHorizontalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabelEnderecoPessoa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEnderecoPessoa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelNumero))
                        .addGap(25, 25, 25)
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComplemento)))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabelCep)
                                .addGap(131, 131, 131)
                                .addComponent(jLabelTelefone)
                                .addGap(54, 54, 54))
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabelBairro)
                                .addGap(231, 231, 231))
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel5))
                                    .addComponent(jTextFieldEstadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCelularPessoa)
                                    .addComponent(jFormattedTextFieldCelularPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jFormattedTextFieldTelefonePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosComplementaresLayout.setVerticalGroup(
            jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosComplementaresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoPessoa)
                    .addComponent(jLabelNumero)
                    .addComponent(jLabelComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnderecoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabel5)
                    .addComponent(jLabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelCelularPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefonePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelularPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPaneCadastroDadosPessoais.addTab("Dados Complementares", jPanelDadosComplementares);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCadastroPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneCadastroDadosPessoais))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneCadastroDadosPessoais)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(907, 844));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFcnpjActionPerformed

    private void jTextFemailPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFemailPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFemailPessoaActionPerformed

    private void jTFidentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidentidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidentidadeActionPerformed

    private void jTFnomePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnomePessoaKeyTyped
//        char c = evt.getKeyChar();
//        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume(); 
    }//GEN-LAST:event_jTFnomePessoaKeyTyped

    public static String formataData(String minhaData) {

        // Data recebida: 29/10/2016
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(minhaData, formato);
        String [] dataSplit = (formato.format(data)).split("/");
        String dia = ""; String mes = ""; String ano = "";

        for(int i=0; i<=3; i++){
            dia = dataSplit[0];
            mes = dataSplit[1];
            ano = dataSplit[2];
        }
        String arrayFinal = ano+mes+dia;
        return arrayFinal;
    }
            
            
//            String telefone = "92/9898.989";
//            telefone = telefone.replaceAll("[^0-9]", "");

//            String [] dataSeparada = minhaData.split(minhaData);
//            String[] strA = minhaData.split("/");
            
//            for(String a: strA){
//                System.out.println(a);
//            }

//            String novaData = minhaData.replace("/", "");
//            System.out.println(strA);

/*
y year
M Month in year
D Day in year
d Day in month
H Hour in day
h Hour in am/pm
m Minute in hour
s Second in minute
S Millisecond Number
*/            
            
//Instancie um DateFormat de acordo com o formato vindo na String, se for dd/MM/yyyy basta fazer assim:
//DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//
//E gerar seu objeto Date fazendo o parse da String
//Date minhaData = dateFormat.parse(textField.getText());
//
//Aí na hora de setar o parâmetro do seu PreparedStatement você cria um java.sql.Date. Isso pode ser feito assim:
//java.sql.Date sqlDate = new java.sql.Date(minhaData.getTime());  
//
//O método getTime() retorna a representação da data em milissegundos, que é utilizada no construtor do java.sql.Date 

//estou levando em consideração que o métoto cliente.getDataNasc(); retorna um objeto do tipo java.util.Date
//java.sql.Date dataSQL = new Date(cliente.getDataNasc().getTime());
//pstmt.setDate(5, dataSQL);            
            
            
//            Como salvar data no banco postgresql
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/exemploJdbc", "root", "");
//            String sql = "insert into contatos" + "(nome,email,endereco,dataNascimento)"+"values(?,?,?,?)";
//            PreparedStatement stmt = con.prepareStatement(sql);
//            stmt.setDate(4, Date.valueOf("1984-10-23"));


//------------FORMATA DATAS-----------------------------------------------------------------------------------

//            Calendar c = Calendar.getInstance();
//            c.set(2013, Calendar.FEBRUARY, 28);
//            java.util.Date data = c.getTime();
//            System.out.println("Data atual sem formatação: "+data);
//
//            //Formata a data
//            DateFormat formataData = DateFormat.getDateInstance();
//            System.out.println("Data atual com formatação: "+ formataData.format(novaData));
//
//            //Formata Hora
//            DateFormat hora = DateFormat.getTimeInstance();
//            System.out.println("Hora formatada: "+hora.format(data));
//
//            //Formata Data e Hora
//            DateFormat dtHora = DateFormat.getDateTimeInstance();
//            System.out.println(dtHora.format(data));

//-------------------------------------------------------------------------------------------------------------

    public boolean validaEmail(){
    
        if(jTextFemailPessoa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        } else{
            String email = jTextFemailPessoa.getText();
            Matcher matcher = Pattern.compile("[-\\w\\.]+@\\w+\\.\\w*\\.*\\w*"
                    ,Pattern.CASE_INSENSITIVE).matcher(email);
            while (matcher.find()) {
                return true;
//                System.out.println(matcher.start() + " - " + matcher.group());
            }
        } 
        return false;
    }
    
    
    private void jBinserirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirPessoaActionPerformed

        boolean retornoEmail = validaEmail();
        if(retornoEmail){
            System.out.println("Email encontrado!");
            jTFnomePessoa.setText(jTextFemailPessoa.getText());
        }else{
            System.out.println("Email não encontrado!");
        } 
        
        
//        if(jFormattedTextFdataNascPessoa.equals("")){
//            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!", 
//            "Aviso", JOptionPane.WARNING_MESSAGE);
//        } else {
//            String minhaData = jFormattedTextFdataNascPessoa.getText();
//            //Data a ser enviada ao banco
//            String dataFormatada = formataData(minhaData);
//
//            String nomePessoa = jTFnomePessoa.getText();
//            
//            String sexo = buttonGroupSexo.getSelection().getActionCommand();
//            sexo = sexo.equals("feminino") ? "FEMININO" : "MASCULINO";
//            String identidade = jTFidentidade.getText();
//            
//            String estado = jComboBoxEstadoIdentidade.getSelectedItem().toString();
//            String orgaoExpeditor = jComboBoxOrgExpeditor.getSelectedItem().toString();
//
//            //tratar campo e-mail
//            String email = jTextFemailPessoa.getText();
//            
//            
////        "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
////        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
////
////private static final Pattern pattern = Pattern.compile(EMAIL_PATTERN, Pattern.CASE_INSENSITIVE            
//            //            String telefone = "92/9898.989";
//            //            telefone = telefone.replaceAll("[^0-9]", "");
//
//            String cpf = jFormattedTextCpf.getSelectedText();
//
////            System.out.print(cpf);
//        }
//        
        
//        String nome_cidade = jTFnomeCidade.getText().toUpperCase();
//        String nome_estado = String.valueOf(jCBestados.getSelectedItem());
//
//        if(nome_estado != "ESCOLHA" && !nome_cidade.isEmpty()){
//            try{
//                Cidade cidades = new Cidade();
//                cidades.setDesc_cidade(nome_cidade);
//                cidades.setEstado_cidade(nome_estado);
//
//                CidadeDao createDao = new CidadeDao();
//                createDao.create(cidades);
//                
//                jTFnomeCidade.setText("");
//                jCBestados.setSelectedItem("ESCOLHA");
//                
//                populajTableCidade();
//                
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!", 
//                "Aviso", JOptionPane.WARNING_MESSAGE);            
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!", 
//            "Aviso", JOptionPane.WARNING_MESSAGE);        
//        }        
        
    }//GEN-LAST:event_jBinserirPessoaActionPerformed

    private void jTextFemailPessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFemailPessoaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFemailPessoaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jBalterarPessoa;
    private javax.swing.JButton jBcancelarPessoa;
    private javax.swing.JButton jBinserirPessoa;
    private javax.swing.JButton jBlimparPessoa;
    private javax.swing.JButton jBremoverPessoa;
    private javax.swing.JComboBox<String> jComboBoxEstadoIdentidade;
    private javax.swing.JComboBox<String> jComboBoxOrgExpeditor;
    private javax.swing.JFormattedTextField jFormattedTextCpf;
    private javax.swing.JFormattedTextField jFormattedTextFcnpj;
    private javax.swing.JFormattedTextField jFormattedTextFdataNascPessoa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularPessoa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePessoa;
    private javax.swing.JLabel jLBemailPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelularPessoa;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEnderecoPessoa;
    private javax.swing.JLabel jLabelNomeMae;
    private javax.swing.JLabel jLabelNomePai;
    private javax.swing.JLabel jLabelNomePessoa;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLestadoIdentidade;
    private javax.swing.JLabel jLidentidade;
    private javax.swing.JLabel jLorgaoExpeditor;
    private javax.swing.JPanel jPCadastroPessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDadosComplementares;
    private javax.swing.JPanel jPanelDadosPessoais;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFidentidade;
    private javax.swing.JTextField jTFnomePessoa;
    private javax.swing.JTabbedPane jTabbedPaneCadastroDadosPessoais;
    private javax.swing.JTable jTcadastroPessoa;
    private javax.swing.JTextField jTextFemailPessoa;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidadeEndereco;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEnderecoPessoa;
    private javax.swing.JTextField jTextFieldEstadoEndereco;
    private javax.swing.JTextField jTextFieldNomeMae;
    private javax.swing.JTextField jTextFieldNomePai;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
